"""Inicializo migraciones

Revision ID: 5407ad989e45
Revises: 
Create Date: 2025-11-15 13:01:52.264562

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5407ad989e45'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categoria', schema=None) as batch_op:
        pass  # No hacemos cambios aquí por ahora

    with op.batch_alter_table('comentario', schema=None) as batch_op:
        pass  # No hacemos cambios aquí por ahora
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categoria', schema=None) as batch_op:
        pass  # No hacemos cambios aquí

    with op.batch_alter_table('comentario', schema=None) as batch_op:
        pass  # No hacemos cambios aquí
    # ### end Alembic commands ###


    with op.batch_alter_table('comentario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contenido', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('usuario_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('post_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_comentario_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_comentario_updated_at'), ['updated_at'], unique=False)
        batch_op.drop_column('texto')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('titulo',
               existing_type=mysql.VARCHAR(length=120),
               type_=sa.String(length=140),
               existing_nullable=False)
        batch_op.alter_column('usuario_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=256),
               type_=sa.String(length=128),
               nullable=True)
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_usuario_created_at'), ['created_at'], unique=False)
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_usuario_created_at'))
        batch_op.alter_column('role',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=256),
               nullable=False)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('usuario_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('titulo',
               existing_type=sa.String(length=140),
               type_=mysql.VARCHAR(length=120),
               existing_nullable=False)

    with op.batch_alter_table('comentario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('texto', mysql.TEXT(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_comentario_updated_at'))
        batch_op.drop_index(batch_op.f('ix_comentario_created_at'))
        batch_op.alter_column('post_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('usuario_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('contenido')

    with op.batch_alter_table('categoria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categoria_nombre'))
        batch_op.create_index(batch_op.f('nombre'), ['nombre'], unique=True)

    # ### end Alembic commands ###
